version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./:/app:cached
    ports:
      - "3080:3000"
  storybook:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./:/app:cached
    command: yarn storybook --ci
    ports:
      - "6006:6006"
