backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images

collections:
  - name: config
    label: Config
    delete: false
    editor:
      preview: false
    files:
      - name: next-seo-config
        label: Next SEO Config
        file: src/next-seo.config.json
        fields:
          - name: title
            label: Title
            widget: string
          - name: description
            label: Description
            widget: string
            pattern: ['.{0,80}', 'Must have at maximum 80 characters']
          - name: canonical
            label: Site URL
            widget: string
          - name: openGraph
            label: Open Graph
            widget: object
            fields:
              - name: type
                label: Type
                widget: select
                options: [website]
                default: website
              - name: url
                label: URL
                widget: relation
                collection: config
                value_field: canonical
                search_fields: [canonical]
                default: canonical
              - name: title
                label: Title
                widget: relation
                collection: config
                value_field: title
                search_fields: [title]
                default: title
              - name: images
                label: Images
                widget: list
                fields:
                  - name: url
                    label: URL
                    required: true
                  - name: width
                    label: Width(px)
                    widget: number
                    required: true
                  - name: height
                    label: Height(px)
                    widget: number
                    required: true
                  - name: alt
                    Label: Alt text
                    widget: string
                    required: true
              - name: locale
                label: Locale
                widget: select
                options: [ja_JP, en_US]
                default: ja_JP
              - name: description
                label: Description
                widget: relation
                collection: config
                value_field: description
                search_fields: [description]
                default: description
          - name: twitter
            label: Twitter
            widget: object
            fields:
              - name: handle
                label: Creator @username
                widget: string
              - name: site
                label: Site @username
                widget: string
              - name: cardType
                label: Card type
                widget: select
                options: [summary, summary_large_image, player]
                default: summary
  - name: contents
    label: Contents
    delete: false
    editor:
      preview: false
    files:
      - name: tv-stations
        label: Tv Stations
        file: src/contents/tv-stations.yml
        fields:
          - name: tv-stations
            label: テレビ局
            widget: list
            fields:
              - label: テレビ局名
                name: name
                widget: string
              - label: プレイリストID
                name: playlistId
                widget: string
              - name: prefectures
                label: 所在地（都道府県）
                widget: list
                fields:
                  - name: name
                    widget: relation
                    collection: yml
                    file: prefectures
                    searchFields:
                      - prefectures.*.name
                    displayFields:
                      - prefectures.*.name
                    valueField: prefectures.*.name
      - name: prefectures
        label: Prefectures
        file: src/contents/prefectures.yml
        fields:
          - name: prefectures
            label: 都道府県
            widget: list
            fields:
              - label: 都道府県名
                name: name
                widget: string
              - label: 緯度
                name: lat
                widget: number
              - label: 経度
                name: lng
                widget: number
