backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images

collections:
  - name: config
    label: Config
    delete: false
    editor:
      preview: false
    files:
      - name: next-seo-config
        label: Next SEO Config
        file: src/next-seo.config.json
        fields:
          - name: title
            label: title
            widget: string
          - name: description
            label: description
            widget: string
            pattern: ['.{,80}', 'Must have at maximum 80 characters']
          - name: canonical
            label: Site URL
            widget: string
          - name: openGraph
            label: open graph
            widget: object
            fields:
              - name: type
                label: Type
                widget: select
                options: ['website']
              - name: locale
                label: Locale
                widget: select
                options: ['ja_JP', 'en_US']
              - name: url
                label: Url
                widget: relation
                collection: config
                value_field: title
                search_field: [title]
          - name: twitter
            label: Twitter account
            widget: string
  - name: contents
    label: Contents
    delete: false
    editor:
      preview: false
    files:
      - name: tv-stations
        label: Tv Stations
        file: src/contents/tv-stations.yml
        fields:
          - name: tv-stations
            label: テレビ局
            widget: list
            fields:
              - { label: テレビ局名, name: name, widget: string}
              - { label: プレイリストID, name: playlistId, widget: string}
              - name: prefectures
                label: 所在地（都道府県）
                widget: list
                fields:
                  - name: name
                    widget: relation
                    collection: yml
                    file: prefectures
                    searchFields:
                      - prefectures.*.name
                    displayFields:
                      - prefectures.*.name
                    valueField: prefectures.*.name
      - name: prefectures
        label: Prefectures
        file: src/contents/prefectures.yml
        fields:
          - name: prefectures
            label: 都道府県
            widget: list
            fields:
              - { label: 都道府県名, name: name, widget: string}
              - { label: 緯度, name: lat, widget: number}
              - { label: 経度, name: lng, widget: number}
